//! HTML and CSV export for Performance Analytics tear sheets.

use crate::performance_analytics::FinancePerformanceSummary;
use crate::performance_report::FinancePerformanceReport;

pub fn performance_summary_csv(report: &FinancePerformanceReport) -> String {
    let summary = &report.bundle.summary;
    let mut lines = vec![
        "metric,value".to_string(),
        format!("label,{}", csv_escape(&report.label)),
        format!("total_return_pct,{:.4}", summary.total_return_pct),
        format!("cagr_pct,{:.4}", summary.cagr_pct),
        format!("ann_volatility_pct,{:.4}", summary.ann_volatility_pct),
        format!("sharpe,{:.4}", summary.sharpe),
        format!("sortino,{:.4}", summary.sortino),
        format!("max_drawdown_pct,{:.4}", summary.max_drawdown_pct),
        format!("calmar,{:.4}", summary.calmar),
        format!("win_rate_pct,{:.4}", summary.win_rate_pct),
        format!("best_period_pct,{:.4}", summary.best_period_pct),
        format!("worst_period_pct,{:.4}", summary.worst_period_pct),
    ];
    if let Some(benchmark) = &report.benchmark {
        lines.push(format!("benchmark_label,{}", csv_escape(&benchmark.label)));
        lines.push(format!("benchmark_total_return_pct,{:.4}", benchmark.total_return_pct));
        lines.push(format!("alpha_pct,{:.4}", benchmark.alpha_pct));
        lines.push(format!("beta,{:.4}", benchmark.beta));
        lines.push(format!("correlation,{:.4}", benchmark.correlation));
    }
    lines.join("\n")
}

pub fn performance_report_html(report: &FinancePerformanceReport) -> String {
    let summary_rows = summary_table_rows(&report.bundle.summary, report.benchmark.as_ref());
    let cumulative_svg = line_chart_svg(
        "Cumulative Return (%)",
        &report.bundle.cumulative_return_pct,
        "#38b86a",
    );
    let drawdown_svg = line_chart_svg(
        "Underwater Drawdown (%)",
        &report.bundle.drawdown_pct,
        "#e05252",
    );
    let rolling_sharpe_svg = line_chart_svg(
        "Rolling Sharpe",
        &sanitize_nan_series(&report.bundle.rolling_sharpe),
        "#4c8bf5",
    );
    let rolling_vol_svg = line_chart_svg(
        "Rolling Volatility (%)",
        &sanitize_nan_series(&report.bundle.rolling_volatility_pct),
        "#c084fc",
    );
    let benchmark_section = report
        .benchmark
        .as_ref()
        .map(|benchmark| {
            format!(
                r#"<section><h2>Benchmark Comparison — {}</h2>
<table><tbody>
<tr><th>Total Return</th><td>{:.2}%</td></tr>
<tr><th>Alpha</th><td>{:.2}%</td></tr>
<tr><th>Beta</th><td>{:.3}</td></tr>
<tr><th>Correlation</th><td>{:.3}</td></tr>
<tr><th>Capture Up</th><td>{:.3}</td></tr>
<tr><th>Capture Down</th><td>{:.3}</td></tr>
</tbody></table>
{}</section>"#,
                html_escape(&benchmark.label),
                benchmark.total_return_pct,
                benchmark.alpha_pct,
                benchmark.beta,
                benchmark.correlation,
                benchmark.capture_ratio_up,
                benchmark.capture_ratio_down,
                line_chart_svg(
                    "Benchmark Cumulative Return (%)",
                    &benchmark.cumulative_return_pct,
                    "#f59e0b",
                ),
            )
        })
        .unwrap_or_default();
    let lineage = if report.lineage.is_empty() {
        "—".to_string()
    } else {
        report.lineage.join(" → ")
    };

    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>{title} — MarketLab Performance Analytics</title>
<style>
body {{ font-family: "Segoe UI", system-ui, sans-serif; background:#111; color:#eee; margin:24px; }}
h1 {{ color:#fbbf24; }}
h2 {{ color:#93c5fd; margin-top:28px; }}
section {{ background:#1a1a1f; border:1px solid #333; border-radius:8px; padding:16px; margin:16px 0; }}
table {{ border-collapse: collapse; width:100%; }}
th, td {{ border:1px solid #333; padding:8px 10px; text-align:left; }}
th {{ background:#222; color:#cbd5e1; width:220px; }}
.meta {{ color:#94a3b8; font-size:13px; margin-bottom:12px; }}
svg {{ width:100%; height:180px; background:#0f0f12; border-radius:6px; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="meta">Graph lineage: {lineage}</p>
<section><h2>Summary Statistics</h2><table><tbody>{summary_rows}</tbody></table></section>
<section>{cumulative_svg}</section>
<section>{drawdown_svg}</section>
<section>{rolling_sharpe_svg}</section>
<section>{rolling_vol_svg}</section>
{benchmark_section}
<p class="meta">Generated by MarketLab Performance Analytics</p>
</body>
</html>"#,
        title = html_escape(&report.label),
        lineage = html_escape(&lineage),
        summary_rows = summary_rows,
        cumulative_svg = cumulative_svg,
        drawdown_svg = drawdown_svg,
        rolling_sharpe_svg = rolling_sharpe_svg,
        rolling_vol_svg = rolling_vol_svg,
        benchmark_section = benchmark_section,
    )
}

fn summary_table_rows(
    summary: &FinancePerformanceSummary,
    benchmark: Option<&crate::performance_analytics::FinanceBenchmarkComparison>,
) -> String {
    let mut rows = vec![
        row("Total Return", &format!("{:.2}%", summary.total_return_pct)),
        row("CAGR", &format!("{:.2}%", summary.cagr_pct)),
        row("Ann. Volatility", &format!("{:.2}%", summary.ann_volatility_pct)),
        row("Sharpe", &format!("{:.3}", summary.sharpe)),
        row("Sortino", &format!("{:.3}", summary.sortino)),
        row("Max Drawdown", &format!("{:.2}%", summary.max_drawdown_pct)),
        row("Calmar", &format!("{:.3}", summary.calmar)),
        row("Win Rate", &format!("{:.1}%", summary.win_rate_pct)),
        row("Best Period", &format!("{:.2}%", summary.best_period_pct)),
        row("Worst Period", &format!("{:.2}%", summary.worst_period_pct)),
    ];
    if let Some(benchmark) = benchmark {
        rows.push(row("Benchmark", &benchmark.label));
        rows.push(row(
            "Benchmark Return",
            &format!("{:.2}%", benchmark.total_return_pct),
        ));
    }
    rows.join("\n")
}

fn row(label: &str, value: &str) -> String {
    format!(
        "<tr><th>{}</th><td>{}</td></tr>",
        html_escape(label),
        html_escape(value)
    )
}

fn line_chart_svg(title: &str, values: &[f64], stroke: &str) -> String {
    if values.is_empty() {
        return format!("<h2>{title}</h2><p>No data</p>");
    }
    let width = 960.0;
    let height = 180.0;
    let pad = 12.0;
    let min = values.iter().copied().fold(f64::INFINITY, f64::min);
    let max = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let span = (max - min).max(1e-6);
    let last = values.len().saturating_sub(1).max(1) as f64;
    let mut points = String::new();
    for (index, value) in values.iter().enumerate() {
        let x = pad + (index as f64 / last) * (width - pad * 2.0);
        let y = pad + (height - pad * 2.0) * (1.0 - (value - min) / span);
        points.push_str(&format!("{x:.1},{y:.1} "));
    }
    format!(
        r#"<h2>{title}</h2><svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg"><polyline fill="none" stroke="{stroke}" stroke-width="2" points="{points}"/></svg>"#
    )
}

fn sanitize_nan_series(values: &[f64]) -> Vec<f64> {
    values
        .iter()
        .map(|value| if value.is_finite() { *value } else { 0.0 })
        .collect()
}

fn csv_escape(value: &str) -> String {
    if value.contains(',') || value.contains('"') {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_string()
    }
}

fn html_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
